### ISSUE TITLE
Failing at recaptcha

### ISSUE THREAD

**Issue by mazshar** [tp223/Driving-Test-Cancellations#1]
There is another recaptcha page after driver license details are entered. This is the one by Incapsula when it detects "malware on computers".

My set up is as follows:

- buster-chrome.zip in directory
- busterEnabled = True

Whatever I try, I can't get passed the reCaptcha page. If I have buster enabled I get the following error:

`test_date_temp = contents_container[0].find_element_by_xpath(".//dd").get_attribute('innerHTML') IndexError: list index out of range`

If I try solving it myself I get the above error also. If I add a solve_captcha for that page the captcha can't be solved.

Any other suggestions?

**Comment by tp223** [comment]
@mazshar could you add the following
```
driver.execute_cdp_cmd('Network.setBlockedURLs', {"urls": ["https://driverpracticaltest.dvsa.gov.uk/nions-to-vnse-the-Bewarfish-so-like-here-hoa-Mon"]})
driver.execute_cdp_cmd('Network.enable', {})
```
after
```
activeDrivers[licenceInfo["licence-id"]] = webdriver.Chrome(executable_path=api["driver"], chrome_options=chrome_options)
driver = activeDrivers[licenceInfo["licence-id"]]
```
It should be around line 298 and let me know if that works. It should block the script which detects bot inputs.

**Comment by mazshar** [comment]
@tp223 that seems to have done the trick. I'll do some further testing and can create a pull request if you like

**Comment by tp223** [comment]
Great! I have just uploaded it so should be good. Let me know if you run into any other issues.
